Repository Midway91/HactoberFest2023, pull requests merged in 2023-10, with the labels that each got.

#30 Create BMI calculator
  HactoberFest/Java/BMI calculator
Labels: hactoberfest

#3 Code for Fibonacci series
  HactoberFest/Java/Fibonacci series
Labels: hactoberfest

#5 Added some Python Codes
  HactoberFest/Python/Rock_Paper_Scissors_Game.py
  HactoberFest/Python/armstrong.py
  HactoberFest/Python/factorial.py
  HactoberFest/Python/quiz.py
Labels: hactoberfest

#7 Frequency of a tuple(python) [HACTOBERFEST 2023]
  HactoberFest/Python/frequenytuple.py
Labels: Hactoberfest2023, hactoberfest

#8 Matrix multiplication(python) [HACTOBERFEST 2023]
  HactoberFest/Python/frequenytuple.py
Labels: Hactoberfest2023, hactoberfest

#10 Added reverse-vowels
  HactoberFest/Java/Reverse_Vowels.java
Labels: hactoberfest

#14 Added examples of quicksort algorithms
  HactoberFest/Java/sort/QuickSort.java
  HactoberFest/Java/sort/RadixSorting.java
Labels: hactoberfest

#15 Create DoublyLinkedList
  HactoberFest/Java/DoublyLinkedList
Labels: hactoberfest

#16 Create computeweightarray
  HactoberFest/Java/computeweightarray
Labels: hactoberfest

#32 Added anagram finder
  HactoberFest/C/anagram.c
Labels: hactoberfest

#25 ArrayLists
  HactoberFest/Java/ArrayLists.java
  HactoberFest/Java/LinkedList.java
  HactoberFest/Java/TreeMaps.java
Labels: hactoberfest

#22 Added LinkedList.java
  HactoberFest/Java/LinkedList.java
Labels: hactoberfest

#17 Update HelloWorld.java
  HactoberFest/Java/HelloWorld.java
Labels: hactoberfest

#18 Create Check_whether_number_is_whole_number_or_not
  HactoberFest/Python/Check_whether_number_is_whole_number_or_not
Labels: hactoberfest

#34 Added CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: Hactoberfest2023, hactoberfest, hactoberfest-accepted

#19 Added heapsort program in Java
  HeapSort.java
Labels: hactoberfest

#20 added Dart folder
  HactoberFest/Dart/hello.dart
Labels: hactoberfest

#21 Added C++ section
  HactoberFest/C++/HelloWorld.cpp
Labels: hactoberfest

#23 Added HelloWord code for Dart language
  HactoberFest/dart/HelloWorld.dart
Labels: hactoberfest

#27 AverageOfNumber
  HactoberFest/Java/AverageOfNumber.java
Labels: hactoberfest

#28 Added DP codes to enhance the repo programs
  Dynamic Programming/1_Climbing_Stairs.cpp
  Dynamic Programming/1_Fibonacci_Series.cpp
  Dynamic Programming/2_Min_Cost_Climbing_Stairs.cpp
Labels: hactoberfest

#29 Build Array from Permutation.java
  HactoberFest/Java/Build Array from Permutation.java
Labels: hactoberfest

#37 Create tree.py
  HactoberFest/Python/tree.py
Labels: Hactoberfest2023, hactoberfest, hactoberfest-accepted

#38 Create factorial.dart
  HactoberFest/factorial.dart
Labels: Hactoberfest2023, hactoberfest, hactoberfest-accepted

#40 phonebook.c
  .vscode/c_cpp_properties.json
  .vscode/launch.json
  .vscode/settings.json
  .vscode/tasks.json
  HactoberFest/C/a.exe
  HactoberFest/C/phonebook.c
  HactoberFest/C/phonebook.exe
  HactoberFest/C/project
Labels: Hactoberfest2023, hactoberfest, hactoberfest-accepted

#41 Create_Floyed_CycleDetection
  Floyed_CycleDetection
Labels: Hactoberfest2023, hactoberfest, hactoberfest-accepted

#42 Create coin_change.cpp
  HactoberFest/C++/Dynamic Programming/coin_change.cpp
Labels: Hactoberfest2023, hactoberfest, hactoberfest-accepted

#43 Added Middle Of LinkedList java
  HactoberFest/Java/MiddleOfLinkedList.java
Labels: Hactoberfest2023, hactoberfest, hactoberfest-accepted

#46 Create LongestCommonsubsequence.cpp
  HactoberFest/C++/Dynamic Programming/LongestCommonsubsequence.cpp
Labels: Hactoberfest2023, hactoberfest, hactoberfest-accepted

#47 Add CaloriesCounter in Dart
  HactoberFest/Dart/CaloriesCounter.dart
Labels: Hactoberfest2023, hactoberfest, hactoberfest-accepted

#48 Niven.cpp
  HactoberFest/C++/CHAPTER 3{LOOPS}/Niven.cpp
Labels: Hactoberfest2023, hactoberfest, hactoberfest-accepted

#49 Create binary.js
  binary.js
Labels: Hactoberfest2023, hactoberfest, hactoberfest-accepted

#50 kotlin projects added
  HactoberFest/Kotlin/helloworld.kt
  HactoberFest/Kotlin/imaginary-numbers.kt
Labels: Hactoberfest2023, hactoberfest, hactoberfest-accepted

#51 mass-rename project added
  HactoberFest/Python/mass_rename.py
Labels: Hactoberfest2023, hactoberfest, hactoberfest-accepted

#52 Create Turtle_race_betting_game.py
  HactoberFest/Python/Turtle_race_betting_game.py
Labels: Hactoberfest2023, hactoberfest, hactoberfest-accepted

#53 0-1 Knapsack problem using dp memoization
  HactoberFest/C++/Dynamic Programming/0-1 Knapsack Problem.cpp
Labels: Hactoberfest2023, hactoberfest, hactoberfest-accepted

#54 made changes in the increment operator
  HactoberFest/C++/CHAPTER 1{BASICS}/09_area_of_circle.cpp
  HactoberFest/C++/CHAPTER 1{BASICS}/09_area_of_circle.exe
  HactoberFest/C++/CHAPTER 3{LOOPS}/06_perfect_number.cpp
Labels: Hactoberfest2023, hactoberfest, hactoberfest-accepted

#55 Bubble Sort in Java
  HactoberFest/Java/BinarySearch.java
  HactoberFest/Java/BubbleSort.java
  HactoberFest/Java/InsertionSort.java
Labels: Hactoberfest2023, hactoberfest, hactoberfest-accepted

#57 Create ArraySecondHighestNumber.java
  HactoberFest/Java/ArraySecondHighestNumber.java
Labels: Hactoberfest2023, hactoberfest, hactoberfest-accepted

#60 890. Find and Replace Pattern
  HactoberFest/C++/890. Find and Replace Pattern
Labels: Hactoberfest2023, hactoberfest, hactoberfest-accepted

#61 Create Shuffle_String.java
  HactoberFest/Java/Shuffle_String.java
Labels: Hactoberfest2023, hactoberfest, hactoberfest-accepted

#65 Added MergeSort.java
  HactoberFest/Java/MergeSort.java
Labels: Hactoberfest2023, hactoberfest, hactoberfest-accepted

#67 Created chess.py
  HactoberFest/Python/chess.py
Labels: Hactoberfest2023, hactoberfest, hactoberfest-accepted

#68 dynamic programming in java
  HactoberFest/Java/Dynamic Proramming/unique_Path.java
  HactoberFest/Java/Dynamic Proramming/unique_PathII.java
Labels: Hactoberfest2023, hactoberfest, hactoberfest-accepted

#69 Create BinaryTreeBST.cpp
  HactoberFest/C++/BinaryTreeBST.cpp
Labels: Hactoberfest2023, hactoberfest, hactoberfest-accepted

#70 Create harshPr1
  harshPr1
Labels: Hactoberfest2023, hactoberfest, hactoberfest-accepted

#71 Implemented stack and queue using C
  HactoberFest/C/Data Structures/Queue.c
  HactoberFest/C/Data Structures/stack.c
Labels: Hactoberfest2023, hactoberfest, hactoberfest-accepted

#72 Finding Kth factor of a number in java
  HactoberFest/Java/sort/KthFactor.java
Labels: Hactoberfest2023, hactoberfest, hactoberfest-accepted

#73 Create bg_color_changer.dart
  HactoberFest/Dart/bg_color_changer.dart
Labels: Hactoberfest2023, hactoberfest, hactoberfest-accepted

#74 Create circlearea.py
  HactoberFest/Python/circlearea.py
Labels: Hactoberfest2023, hactoberfest, hactoberfest-accepted

#75 add calculator.py
  HactoberFest/Python/calculator.py
Labels: Hactoberfest2023, hactoberfest, hactoberfest-accepted

#76 Added Merge Sort JS
  HactoberFest/JavaScript/MergeSort.js
Labels: Hactoberfest2023, hactoberfest, hactoberfest-accepted

#78 Create SimpleCalculator using Java
  HactoberFest/Java/SimpleCalculator.py
Labels: Hactoberfest2023, hactoberfest, hactoberfest-accepted

#79 Create_Print_2DArray_Like_Wave
  Print_Like_Wave
Labels: Hactoberfest2023, hactoberfest, hactoberfest-accepted

#80 Added Trie Data Structure
  HactoberFest/Python/TrieDataStructure.py
Labels: Hactoberfest2023, hacktoberfest, hacktoberfest-accepted

#81 array_maximum_number
  HactoberFest/Java/Array_maximum_number.java
Labels: Hactoberfest2023, hacktoberfest, hacktoberfest-accepted

#82 Monotonic stack in java
  HactoberFest/Java/Monotonic_Stack/Largest_rectangle_in_histogram.java
  HactoberFest/Java/Monotonic_Stack/Next_Greater_Element.java
  HactoberFest/Java/Monotonic_Stack/Next_Greater_Element2.java
  HactoberFest/Java/Monotonic_Stack/trapping_rain_water.java
Labels: Hactoberfest2023, hacktoberfest, hacktoberfest-accepted

#84 Second Largest file added
  HactoberFest/Java/SecondLargest.java
Labels: Hactoberfest2023, hacktoberfest, hacktoberfest-accepted

#85 Create Flower_Turtle1
  HactoberFest/Python/Flower_Turtle1
Labels: Hactoberfest2023, hacktoberfest, hacktoberfest-accepted

#86 Create palindrome.py
  HactoberFest/Python/palindrome.py
Labels: Hactoberfest2023, hacktoberfest, hacktoberfest-accepted

#87 Create Merge Sort
  HactoberFest/Python/Merge Sort
Labels: Hactoberfest2023, hacktoberfest, hacktoberfest-accepted

#88 Add files via upload
  HactoberFest/C/Data Structures/pascaltree.c
Labels: Hactoberfest2023, hacktoberfest, hacktoberfest-accepted

#89 Create 08_three_sum_triplet.cpp
  HactoberFest/C++/CHAPTER 7{FUNCTIONS}/08_three_sum_triplet.cpp
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#90 the number of possible unique paths
  HactoberFest/C++/Dynamic Programming/uniquePath.cpp
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#91 Create javaprint.js
  HactoberFest/JavaScript/javaprint.js
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#92 Create array.java
  HactoberFest/Java/arrayall.java
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#94 Create array_sum_recursion.cpp
  HactoberFest/C++/CHAPTER 4{ARRAYS}/array_sum_recursion.cpp
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#95 Create factorial.cpp
  HactoberFest/C++/CHAPTER 7{FUNCTIONS}/factorial.cpp
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#96 Create heapSort.py
  HactoberFest/Python/heapSort.py
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#98 Create heapSort.py
  HactoberFest/Python/heapSort.py
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#102 Add/Python-longest path in a matrix
  HactoberFest/Python/Longest Path in Matrix.py
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#103 Solved #100
  HactoberFest/Java/QuickSort.java
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#104 Linear Search Python #99
  HactoberFest/Python/Linear_Search.py
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#106 Create leap_year.py
  leap_year.py
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#107 Dart/sample code
  HactoberFest/Dart/onboard_screen.dart
  HactoberFest/Dart/screen_responsive_widget.dart
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#108 Create Longest Substring Without Repeating Character
  HactoberFest/C++/Longest Substring Without Repeating Character
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#110 Create Palindrome_checker
  Palindrome_checker
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#112 Added PalindromeChecker.java
  HactoberFest/Java/PalindromeChecker.java
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#114 Create binary_search.py
  HactoberFest/Python/binary_search.py
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#115 Create BinarySearch.java
  BinarySearch.java
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#117 commit
  HactoberFest/Python/passsword.py
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#118 To Do List
  todolist.html
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#120 Create Sketch.py
  HactoberFest/Python/Sketch.py
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#122 Added 'Rat in a Maze' Backtracking Solution
  HactoberFest/C++/Backtracking/Rat_in_a_maze.cpp
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#123 Create decimal_to_binary.cpp
  decimal_to_binary
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#124 Create calculator.cpp
  calculator.cpp
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#127 Create MatrixRepesentaionGraph.cpp
  MatrixRepesentaionGraph.cpp
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#130 Create Hangman.cpp
  Hangman.cpp
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#131 Create Determinant_solver.cpp
  Determinant_solver.cpp
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#132 feat: adding code for getting the power of a number using recursion
  HactoberFest/Python/power_using_recursion.py
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#134 Quick Sort - DC
  HactoberFest/Java/QuickSortDC.txt
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#133 just a python scripts that lets you download youtube videos just by pasting their link
  HactoberFest/Python/YoutubeDownloader.py
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#136 Create Asteroid_Collision.py
  Asteroid_Collision.py
  Binary_Tree_Right_View.py
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#137 Add a javascript app
  HactoberFest/JavaScript/NumberGuesser/app/initLang.js
  HactoberFest/JavaScript/NumberGuesser/app/sortNumber.js
  HactoberFest/JavaScript/NumberGuesser/app/validation.js
  HactoberFest/JavaScript/NumberGuesser/app/voiceRecognition.js
  HactoberFest/JavaScript/NumberGuesser/index.html
  HactoberFest/JavaScript/NumberGuesser/styles.css
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#138 Created a Bank Management System program in c
  HactoberFest/Bank_Management.c
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#139 heap sort added using c++
  HactoberFest/C++/SORT/heap_sort.cpp
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#140 Create odd_even_linked_list.cpp
  HactoberFest/C++/odd_even_linked_list.cpp
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#141 Create ThreeSum.java
  HactoberFest/Java/ThreeSum.java
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#145 Solved issue #143 (added bubble sort algorithm in python )
  HactoberFest/Python/Bubblesort.py
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#146 Add Tictactoe file
  HactoberFest/JavaScript/Tictactoe/flower.png
  HactoberFest/JavaScript/Tictactoe/tictac.css
  HactoberFest/JavaScript/Tictactoe/tictac.html
  HactoberFest/JavaScript/Tictactoe/tictac.js
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#148 Added python problems
  HactoberFest/Python/champagnetower.py
  HactoberFest/Python/number_of_goodpairs.py
  HactoberFest/Python/sort_array_by_parity.py
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#149 Hacktoberfest2023
  HactoberFest/Python/avatar.py
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#151 added a cpp file of palindrone.cpp
  HactoberFest/C++/palindrone.cpp
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#152 solved issue #147
  HactoberFest/HTML_CSS/Scientific calculator.html
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#155 Create Leetcode_200_no_of_islands.cpp
  HactoberFest/C++/graph/Leetcode_200_no_of_islands.cpp
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#156 Added Print_all_subset.cpp
  HactoberFest/C++/Backtracking/Print_all_subset.cpp
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#157 Added Dijkstra’s Algorithm
  HactoberFest/JavaScript/Dijkstra'sAlgorithm.js
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#158 add magicgame.cpp in Hactoberfest/C++
  HactoberFest/C++/magicgame.c
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#159 Implement of a Kruskal's algorithm
  HactoberFest/Java/Implement of a Kruskal's algorithm
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#161 Create ROMAN_TO_INTEGER.cpp
  HactoberFest/C++/ROMAN_TO_INTEGER.cpp
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#163 Added Registration Form using HTML and CSS
  HactoberFest/HTML_CSS/registrationForm.html
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#167 Added Python Code
  HactoberFest/Python/KadanesAlgo.py
  HactoberFest/Python/fact_to_array.py
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#169 Created a basic_calculator program for python
  HactoberFest/Python/basic_calc.py
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#170 created a Number Guessing Game in java
  HactoberFest/Java/NumberGame.java
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#171 Panagram in C++
  HactoberFest/C++/panagram.cpp
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#173 added programs for C++ STL Library
  HactoberFest/C++/CHAPTER 20{STL}/07_nesting_of_vectors.cpp
  HactoberFest/C++/CHAPTER 20{STL}/07_nesting_of_vectors.exe
  HactoberFest/C++/CHAPTER 20{STL}/08_unorderedmaps.cpp
  HactoberFest/C++/CHAPTER 20{STL}/08_unorderedmaps.exe
  HactoberFest/C++/CHAPTER 20{STL}/09_sets.cpp
  HactoberFest/C++/CHAPTER 20{STL}/09_sets.exe
  HactoberFest/C++/CHAPTER 20{STL}/10_nesting_maps_pairs.cpp
  HactoberFest/C++/CHAPTER 20{STL}/10_nesting_maps_pairs.exe
  HactoberFest/C++/CHAPTER 20{STL}/11_stack_queues.cpp
  HactoberFest/C++/CHAPTER 20{STL}/11_stack_queues.exe
  HactoberFest/C++/CHAPTER 20{STL}/12_lower_upper_bound.cpp
  HactoberFest/C++/CHAPTER 20{STL}/12_lower_upper_bound.exe
  HactoberFest/C++/CHAPTER 20{STL}/13_iterators.cpp
  HactoberFest/C++/CHAPTER 20{STL}/13_iterators.exe
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#178 Online Reservation System in Java
  HactoberFest/Java/OnlineReservation.java
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#179 Added N-Queens.py
  HactoberFest/Python/N_Queens.py
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#180 Create LinkedList.c
  HactoberFest/C/Data Structures/LinkedList.c
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#181 Update 06_binary_search.cpp
  HactoberFest/C++/CHAPTER 4{ARRAYS}/06_binary_search.cpp
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#184 Clothing Website Home Page using HTML AND CSS
  HactoberFest/HTML_CSS/clothingWebisteHomePage/.prettierrc
  HactoberFest/HTML_CSS/clothingWebisteHomePage/README.md
  HactoberFest/HTML_CSS/clothingWebisteHomePage/img/card-lazy.jpg
  HactoberFest/HTML_CSS/clothingWebisteHomePage/img/card.jpg
  HactoberFest/HTML_CSS/clothingWebisteHomePage/img/digital-lazy.jpg
  HactoberFest/HTML_CSS/clothingWebisteHomePage/img/digital.jpg
  HactoberFest/HTML_CSS/clothingWebisteHomePage/img/grow-lazy.jpg
  HactoberFest/HTML_CSS/clothingWebisteHomePage/img/grow.jpg
  HactoberFest/HTML_CSS/clothingWebisteHomePage/img/hero.png
  HactoberFest/HTML_CSS/clothingWebisteHomePage/img/icon.png
  HactoberFest/HTML_CSS/clothingWebisteHomePage/img/icons.svg
  HactoberFest/HTML_CSS/clothingWebisteHomePage/img/img-1.jpg
  HactoberFest/HTML_CSS/clothingWebisteHomePage/img/img-2.jpg
  HactoberFest/HTML_CSS/clothingWebisteHomePage/img/img-3.jpg
  HactoberFest/HTML_CSS/clothingWebisteHomePage/img/img-4.jpg
  HactoberFest/HTML_CSS/clothingWebisteHomePage/img/logo.png
  HactoberFest/HTML_CSS/clothingWebisteHomePage/img/men-1.jpg
  HactoberFest/HTML_CSS/clothingWebisteHomePage/img/men-2.jpg
  HactoberFest/HTML_CSS/clothingWebisteHomePage/img/men-3.jpg
  HactoberFest/HTML_CSS/clothingWebisteHomePage/img/user-1.jpg
  HactoberFest/HTML_CSS/clothingWebisteHomePage/img/user-2.jpg
  HactoberFest/HTML_CSS/clothingWebisteHomePage/img/user-3.jpg
  HactoberFest/HTML_CSS/clothingWebisteHomePage/index.html
  HactoberFest/HTML_CSS/clothingWebisteHomePage/script.js
  HactoberFest/HTML_CSS/clothingWebisteHomePage/style.css
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#185 Create TowerOFHanoi.cpp
  TowerOFHanoi.cpp
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#189 added NQueens algorithm using Backtracking
  HactoberFest/Java/Backtracking/NQueens.java
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#190 Added Fibonaccinumber.cpp
  Fibonaccinumber.cpp
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#191 added Circular Linked List code
  HactoberFest/C++/CircularLinkedList.cpp
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#193 Create 463. Island Perimeter.cpp
  HactoberFest/C++/graph/463. Island Perimeter.cpp
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#194 Hacktoberfest 2023
  WordCounterapplication.java
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#195 Added 2 files
  HactoberFest/C/polynomial representation.c
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#196 Shell Sort Algorithm
  HactoberFest/C++/SORT/shell_sort.cpp
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#227 Revamp and Enhance HacktoberFest2023 Readme file
  README.md
  hf10_banner_sponsors_1032x600.png
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#226 Fibonaccinumber with dp
  Fibonaccinumber.cpp
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#198 Create Tower of Hanoi.py
  Tower of Hanoi.py
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#201 Battleship game developed for learning C/C++ programming.
  HactoberFest/C++/NavalBattle.cpp
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#202 Create kadane's algorithm.cpp
  HactoberFest/C++/CHAPTER 4{ARRAYS}/kadane's algorithm.cpp
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#203 Program for Selection sort in Kotlin
  HactoberFest/Kotlin/SelectionSort.kt
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#204 Program for Bubble sort in Kotlin
  HactoberFest/Kotlin/BubbleSort.kt
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#205 Program for Quick sort in Kotlin
  HactoberFest/Kotlin/QuickSort.kt
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#206 Program for Merge sort in Kotlin
  HactoberFest/Kotlin/MergeSort.kt
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#207 Program for Heap sort in Kotlin
  HactoberFest/Kotlin/HeapSort.kt
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#209 C++ Contribution
  HactoberFest/C++/area.cpp
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#210 Program for Insertion sort in Kotlin
  HactoberFest/Kotlin/InsertionSort.kt
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#211 create Fractional knapsack
  Fractional_Knapsack.cpp
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#212 Create Binary Tree Maximum Path Sum.cpp
  HactoberFest/C++/Dynamic Programming/Binary Tree Maximum Path Sum.cpp
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#214 Create stopwatch
  stopwatch
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#217 Created a detailed shell sorting algorithm
  HactoberFest/C++/SORT/Shell_Sort.cpp
  HactoberFest/C++/SORT/shell_sort.cpp
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#219 Added a MERN stack project along with a C++ program
  HactoberFest/C++/Implement_Stack_using-Queues_By_push.cpp
  HactoberFest/MERN/TODOList-App/.gitignore
  HactoberFest/MERN/TODOList-App/client/README.md
  HactoberFest/MERN/TODOList-App/client/package-lock.json
  HactoberFest/MERN/TODOList-App/client/package.json
  HactoberFest/MERN/TODOList-App/client/public/android-chrome-192x192.png
  HactoberFest/MERN/TODOList-App/client/public/android-chrome-512x512.png
  HactoberFest/MERN/TODOList-App/client/public/apple-touch-icon.png
  HactoberFest/MERN/TODOList-App/client/public/favicon-16x16.png
  HactoberFest/MERN/TODOList-App/client/public/favicon-32x32.png
  HactoberFest/MERN/TODOList-App/client/public/favicon.ico
  HactoberFest/MERN/TODOList-App/client/public/index.html
  HactoberFest/MERN/TODOList-App/client/public/manifest.json
  HactoberFest/MERN/TODOList-App/client/public/site.webmanifest
  HactoberFest/MERN/TODOList-App/client/src/App.css
  HactoberFest/MERN/TODOList-App/client/src/App.js
  HactoberFest/MERN/TODOList-App/client/src/App.test.js
  HactoberFest/MERN/TODOList-App/client/src/index.css
  HactoberFest/MERN/TODOList-App/client/src/index.js
  HactoberFest/MERN/TODOList-App/client/src/reportWebVitals.js
  HactoberFest/MERN/TODOList-App/client/src/setupTests.js
  HactoberFest/MERN/TODOList-App/client/src/todoComponent/DataAdder.js
  HactoberFest/MERN/TODOList-App/client/src/todoComponent/Head.js
  HactoberFest/MERN/TODOList-App/client/src/todoComponent/ShowData.js
  HactoberFest/MERN/TODOList-App/package.json
  HactoberFest/MERN/TODOList-App/server/config/db.js
  HactoberFest/MERN/TODOList-App/server/controllers/data_controllers.js
  HactoberFest/MERN/TODOList-App/server/models/data_models.js
  HactoberFest/MERN/TODOList-App/server/package-lock.json
  HactoberFest/MERN/TODOList-App/server/package.json
  HactoberFest/MERN/TODOList-App/server/routes/data_routes.js
  HactoberFest/MERN/TODOList-App/server/server.js
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#220 Create quick_sort.cpp
  quick_sort.cpp
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#222 Create BubbleSort.cpp
  HactoberFest/C++/SORT/BubbleSort.cpp
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#223 Create SelectionSort.cpp
  HactoberFest/C++/SORT/SelectionSort.cpp
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#224 new BMI calculator
  HactoberFest/Python/BMI Calculator.py
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted
